export type Database = {
  public: {
    Tables: {
      markets: {
        Row: {
          accent: string;
          active_agents: string;
          avatar: "image" | "emoji";
          badge: string | null;
          brief: string;
          category: string;
          confidence: string;
          created_at: string;
          creator_email: string | null;
          creator_privy_user_id: string;
          deliverables: string[];
          description: string;
          emoji: string | null;
          examples: string[];
          id: string;
          image: string | null;
          image_alt: string | null;
          name: string;
          play_count: number;
          plays: string;
          price: string;
          requests: string;
          slug: string;
          status: "published" | "draft" | "archived";
          timeline: string;
          updated_at: string;
          volume: string;
        };
        Insert: {
          accent?: string;
          active_agents?: string;
          avatar?: "image" | "emoji";
          badge?: string | null;
          brief?: string;
          category: string;
          confidence?: string;
          created_at?: string;
          creator_email?: string | null;
          creator_privy_user_id: string;
          deliverables?: string[];
          description: string;
          emoji?: string | null;
          examples?: string[];
          id?: string;
          image?: string | null;
          image_alt?: string | null;
          name: string;
          play_count?: number;
          plays?: string;
          price?: string;
          requests?: string;
          slug: string;
          status?: "published" | "draft" | "archived";
          timeline?: string;
          updated_at?: string;
          volume?: string;
        };
        Update: {
          accent?: string;
          active_agents?: string;
          avatar?: "image" | "emoji";
          badge?: string | null;
          brief?: string;
          category?: string;
          confidence?: string;
          created_at?: string;
          creator_email?: string | null;
          creator_privy_user_id?: string;
          deliverables?: string[];
          description?: string;
          emoji?: string | null;
          examples?: string[];
          id?: string;
          image?: string | null;
          image_alt?: string | null;
          name?: string;
          play_count?: number;
          plays?: string;
          price?: string;
          requests?: string;
          slug?: string;
          status?: "published" | "draft" | "archived";
          timeline?: string;
          updated_at?: string;
          volume?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
