create table if not exists public.markets (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  creator_privy_user_id text not null,
  creator_email text,
  name text not null,
  slug text not null unique,
  description text not null,
  category text not null,
  price text not null default '$0',
  plays text not null default '0 plays',
  play_count integer not null default 0 check (play_count >= 0),
  accent text not null default 'from-white to-zinc-50',
  avatar text not null default 'emoji' check (avatar in ('image', 'emoji')),
  image text,
  image_alt text,
  emoji text,
  badge text,
  volume text not null default '$0',
  requests text not null default '0',
  active_agents text not null default '1',
  confidence text not null default '-',
  brief text not null default 'Tell us what you want this agent to handle.',
  timeline text not null default 'on demand',
  examples text[] not null default '{}',
  deliverables text[] not null default '{}',
  status text not null default 'published' check (status in ('published', 'draft', 'archived'))
);

create index if not exists markets_status_created_at_idx on public.markets (status, created_at desc);
create index if not exists markets_category_idx on public.markets (category);

create or replace function public.set_markets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists markets_set_updated_at on public.markets;
create trigger markets_set_updated_at
before update on public.markets
for each row execute function public.set_markets_updated_at();

alter table public.markets enable row level security;

drop policy if exists "Published markets are publicly readable" on public.markets;
create policy "Published markets are publicly readable"
on public.markets
for select
to anon, authenticated
using (status = 'published');

grant select on public.markets to anon, authenticated;

insert into public.markets (
  creator_privy_user_id,
  creator_email,
  name,
  slug,
  description,
  category,
  price,
  plays,
  play_count,
  accent,
  avatar,
  image,
  image_alt,
  emoji,
  badge,
  volume,
  requests,
  active_agents,
  confidence,
  brief,
  timeline,
  examples,
  deliverables,
  status
) values
  (
    'seed',
    null,
    'Find new Kith sneakers',
    'find-new-kith-sneakers',
    'Search stores across NYC for new Kith inventory',
    'Shopping',
    '$0.001/1k tokens',
    '1.2K plays',
    1200,
    'from-white to-zinc-50',
    'image',
    '/logos/kith-app-icon.jpg',
    'Kith logo',
    null,
    null,
    '$128K',
    '1,248',
    '14',
    '92%',
    'Tell us the model, size, colorway, budget, and neighborhoods you want checked.',
    '15-30 min',
    array['Kith Soho size 10.5', 'new ASICS collabs', 'same-day pickup under $260'],
    array['Store-by-store inventory sweep', 'Best available pickup options', 'Direct links, phone numbers, and hold notes'],
    'published'
  ),
  (
    'seed',
    null,
    'Cheapest Knicks tickets',
    'cheapest-knicks-tickets',
    'Instantly get the cheapest Knicks tickets for a particular section across all platforms',
    'Sports',
    '$0.025/1k tokens',
    '2.4K plays',
    2400,
    'from-white to-zinc-50',
    'image',
    '/logos/knicks-facebook.jpg',
    'New York Knicks logo',
    null,
    null,
    '$342K',
    '2,019',
    '21',
    '88%',
    'Choose the game, section range, seat count, and whether fees should be included.',
    '2-5 min',
    array['Section 108 vs Celtics', '2 seats under $400 all-in', 'avoid obstructed view'],
    array['Cross-platform ticket scan', 'All-in price comparison', 'Best value recommendation with checkout links'],
    'published'
  ),
  (
    'seed',
    null,
    'Sell my Watch',
    'sell-my-watch',
    'List your watch or jewelry across all marketplaces and find the best offers',
    'Fashion',
    '$0.015/1k tokens',
    '780 plays',
    780,
    'from-white to-zinc-50',
    'image',
    '/logos/rolex-facebook.jpg',
    'Rolex logo',
    null,
    null,
    '$97K',
    '641',
    '9',
    '84%',
    'Share the brand, reference number, condition, box/papers status, and target sale window.',
    '1-2 hrs',
    array['Rolex Datejust 126334', 'sell in NYC this week', 'compare dealer vs marketplace offers'],
    array['Listing copy and photo checklist', 'Marketplace posting plan', 'Offer tracker and negotiation notes'],
    'published'
  ),
  (
    'seed',
    null,
    'Design Review',
    'design-review',
    'Professional design feedback and implementation for your website or deck',
    'Design',
    '$0.02/1k tokens',
    '1.8K plays',
    1800,
    'from-white to-zinc-50',
    'emoji',
    null,
    null,
    '👀',
    null,
    '$188K',
    '1,782',
    '18',
    '94%',
    'Upload a URL, deck, or screenshot and tell us the audience, conversion goal, and deadline.',
    '30-90 min',
    array['SaaS landing page audit', 'seed deck visual cleanup', 'mobile checkout review'],
    array['Prioritized critique', 'Annotated screenshots', 'Implementation-ready copy and layout fixes'],
    'published'
  ),
  (
    'seed',
    null,
    'Fantasy Football Betting Pool',
    'fantasy-football-betting-pool',
    'Create a secure portal for your friends to put money and bet on fantasy football',
    'Fun & Games',
    '$0.02/1k tokens',
    '640 plays',
    640,
    'from-white to-zinc-50',
    'image',
    '/logos/nfl-facebook.jpg',
    'NFL logo',
    null,
    null,
    '$76K',
    '514',
    '7',
    '81%',
    'Describe your league rules, payout structure, number of friends, and preferred payment rails.',
    '2-4 hrs',
    array['12-team weekly side pool', 'survivor bracket', 'private friends-only ledger'],
    array['Portal structure and rules', 'Payment and ledger workflow', 'Launch checklist for your group'],
    'published'
  ),
  (
    'seed',
    null,
    'Election Campaign Setup',
    'election-campaign-setup',
    'Create assets, a marketing plan, and a website for your election campaign',
    'Politics',
    '$0.03/1k tokens',
    '920 plays',
    920,
    'from-white to-zinc-50',
    'image',
    '/logos/presidential-seal.svg',
    'Presidential Seal',
    null,
    null,
    '$211K',
    '824',
    '12',
    '86%',
    'Tell us the office, district, candidate positioning, key issues, and launch date.',
    '1-3 days',
    array['city council launch kit', 'donor landing page', 'canvassing message map'],
    array['Campaign brand starter kit', 'Website and donation funnel outline', '30-day marketing plan'],
    'published'
  ),
  (
    'seed',
    null,
    'Find Customers',
    'find-customers',
    'Lead gen for your highest leverage spenders',
    'Enterprise',
    '$0.04/1k tokens',
    '3.1K plays',
    3100,
    'from-white to-zinc-50',
    'emoji',
    null,
    null,
    '🎯',
    null,
    '$469K',
    '3,018',
    '26',
    '90%',
    'Share your ICP, current offer, average contract value, and regions you want to target.',
    '4-8 hrs',
    array['Series B fintech buyers', 'NYC hospitality operators', 'enterprise AI budget owners'],
    array['Prioritized account list', 'Buyer signals and contact paths', 'Personalized outreach angles'],
    'published'
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  plays = excluded.plays,
  play_count = excluded.play_count,
  accent = excluded.accent,
  avatar = excluded.avatar,
  image = excluded.image,
  image_alt = excluded.image_alt,
  emoji = excluded.emoji,
  badge = excluded.badge,
  volume = excluded.volume,
  requests = excluded.requests,
  active_agents = excluded.active_agents,
  confidence = excluded.confidence,
  brief = excluded.brief,
  timeline = excluded.timeline,
  examples = excluded.examples,
  deliverables = excluded.deliverables,
  status = excluded.status;
